#include "../../core.h"

LoadScriptingComponent(
    memory,
    [](Plugin* plugin, EContext* state)
    {
        GetGlobalNamespace(state)
            .beginClass<PluginMemory>("Memory")
            .addConstructor<>()
            .addFunction("LoadFromAddress", &PluginMemory::LoadFromAddress)
            .addFunction("LoadFromSignatureName", &PluginMemory::LoadFromSignatureName)
            .addFunction("LoadFromSignature", &PluginMemory::LoadFromSignature)
            .addFunction("AddOffsetByName", &PluginMemory::AddOffsetByName)
            .addFunction("AddOffset", &PluginMemory::AddOffset)
            .addFunction("RemoveOffsetByName", &PluginMemory::RemoveOffsetByName)
            .addFunction("RemoveOffset", &PluginMemory::RemoveOffset)
            .addFunction("AccessVTable", &PluginMemory::AccessVTable)
            .addFunction("AccessVTableFromOffset", &PluginMemory::AccessVTableFromOffset)
            .addFunction("AccessedVTable", &PluginMemory::AccessedVTable)
            .addFunction("AccessIndexFromOffset", &PluginMemory::AccessIndexFromOffset)
            .addFunction("AccessIndex", &PluginMemory::AccessIndex)
            .addFunction("Allocate", &PluginMemory::Allocate)
            .addFunction("Deallocate", &PluginMemory::Deallocate)
            .addFunction("Clear", &PluginMemory::Clear)
            .addFunction("SetBool", &PluginMemory::SetBool)
            .addFunction("SetInt", &PluginMemory::SetInt)
            .addFunction("SetInt64", &PluginMemory::SetInt64)
            .addFunction("SetUint", &PluginMemory::SetUint)
            .addFunction("SetUint64", &PluginMemory::SetUint64)
            .addFunction("SetFloat", &PluginMemory::SetFloat)
            .addFunction("SetDouble", &PluginMemory::SetDouble)
            .addFunction("SetVector", &PluginMemory::SetVector)
            .addFunction("SetVector2D", &PluginMemory::SetVector2D)
            .addFunction("SetVector4D", &PluginMemory::SetVector4D)
            .addFunction("SetColor", &PluginMemory::SetColor)
            .addFunction("SetQAngle", &PluginMemory::SetQAngle)
            .addFunction("GetBool", &PluginMemory::GetBool)
            .addFunction("GetInt", &PluginMemory::GetInt)
            .addFunction("GetInt64", &PluginMemory::GetInt64)
            .addFunction("GetUint", &PluginMemory::GetUint)
            .addFunction("GetUint64", &PluginMemory::GetUint64)
            .addFunction("GetFloat", &PluginMemory::GetFloat)
            .addFunction("GetDouble", &PluginMemory::GetDouble)
            .addFunction("GetVector", &PluginMemory::GetVector)
            .addFunction("GetVector2D", &PluginMemory::GetVector2D)
            .addFunction("GetVector4D", &PluginMemory::GetVector4D)
            .addFunction("GetColor", &PluginMemory::GetColor)
            .addFunction("GetQAngle", &PluginMemory::GetQAngle)
            .addFunction("GetPtr", &PluginMemory::GetPtr)
            .addFunction("IsValid", &PluginMemory::IsValid)
            .endClass();
    }
)