#ifndef _gamephase_h
#define _gamephase_h

enum class GamePhase
{
    GAMEPHASE_WARMUP_ROUND,
    GAMEPHASE_PLAYING_STANDARD,    
    GAMEPHASE_PLAYING_FIRST_HALF,
    GAMEPHASE_PLAYING_SECOND_HALF,
    GAMEPHASE_HALFTIME,
    GAMEPHASE_MATCH_ENDED,    
    GAMEPHASE_MAX
};

#endif