#include "../../core.h"

LoadLuaScriptingComponent(
    centitykeyvalues,
    [](LuaPlugin* plugin, lua_State* state)
    {
        luabridge::getGlobalNamespace(state)
            .beginClass<PluginCEntityKeyValues>("CEntityKeyValues")
            .addConstructor<void (*)()>()
            .addFunction("GetBool", &PluginCEntityKeyValues::GetBool)
            .addFunction("GetInt", &PluginCEntityKeyValues::GetInt)
            .addFunction("GetUint", &PluginCEntityKeyValues::GetUint)
            .addFunction("GetInt64", &PluginCEntityKeyValues::GetInt64)
            .addFunction("GetUint64", &PluginCEntityKeyValues::GetUint64)
            .addFunction("GetFloat", &PluginCEntityKeyValues::GetFloat)
            .addFunction("GetDouble", &PluginCEntityKeyValues::GetDouble)
            .addFunction("GetString", &PluginCEntityKeyValues::GetString)
            .addFunction("GetPtr", &PluginCEntityKeyValues::GetPtr)
            .addFunction("GetStringToken", &PluginCEntityKeyValues::GetStringToken)
            .addFunction("GetColor", &PluginCEntityKeyValues::GetColor)
            .addFunction("GetVector", &PluginCEntityKeyValues::GetVector)
            .addFunction("GetVector2D", &PluginCEntityKeyValues::GetVector2D)
            .addFunction("GetVector4D", &PluginCEntityKeyValues::GetVector4D)
            .addFunction("GetQAngle", &PluginCEntityKeyValues::GetQAngle)
            .addFunction("SetBool", &PluginCEntityKeyValues::SetBool)
            .addFunction("SetInt", &PluginCEntityKeyValues::SetInt)
            .addFunction("SetUint", &PluginCEntityKeyValues::SetUint)
            .addFunction("SetInt64", &PluginCEntityKeyValues::SetInt64)
            .addFunction("SetUint64", &PluginCEntityKeyValues::SetUint64)
            .addFunction("SetFloat", &PluginCEntityKeyValues::SetFloat)
            .addFunction("SetDouble", &PluginCEntityKeyValues::SetDouble)
            .addFunction("SetString", &PluginCEntityKeyValues::SetString)
            .addFunction("SetPtr", &PluginCEntityKeyValues::SetPtr)
            .addFunction("SetStringToken", &PluginCEntityKeyValues::SetStringToken)
            .addFunction("SetColor", &PluginCEntityKeyValues::SetColor)
            .addFunction("SetVector", &PluginCEntityKeyValues::SetVector)
            .addFunction("SetVector2D", &PluginCEntityKeyValues::SetVector2D)
            .addFunction("SetVector4D", &PluginCEntityKeyValues::SetVector4D)
            .addFunction("SetQAngle", &PluginCEntityKeyValues::SetQAngle)
            .endClass();
    }
)